# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('reminderTime', models.DateTimeField()),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2017, 4, 20, 7, 37, 23, 725327, tzinfo=utc))),
                ('modifiedTime', models.DateTimeField(default=datetime.datetime(2017, 4, 20, 7, 37, 23, 725364, tzinfo=utc))),
            ],
            options={
                'db_table': 'Reminder',
            },
        ),
    ]
