# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2017, 4, 12, 11, 25, 18, 346532, tzinfo=utc))),
                ('modifiedTime', models.DateTimeField(default=datetime.datetime(2017, 4, 12, 11, 25, 18, 346532, tzinfo=utc))),
            ],
            options={
                'db_table': 'Reminder',
            },
        ),
    ]
