# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_blog', '0004_auto_20170419_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 12, 39, 21, 488127, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 12, 39, 21, 488158, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='reminder',
            table='RemindMe',
        ),
    ]
